all: README.md

README.md:
	echo "Title: The Guessing Game, implemented in Bash" > README.md
	echo "Created on: " >> README.md
	date >> README.md
	echo "Number of lines of code: " >> README.md 
	wc -l guessinggame.sh >> README.md
clean:
	rm README.md
